table ae_by_cohort
	lineageTag: 66257b65-29db-5d0e-80f8-ee6eb2acddf7

	column cohort
		dataType: string
		lineageTag: baf5535f-8d9d-54ae-8bb7-91ef3716b25f
		sourceColumn: cohort

	column event_count
		dataType: int64
		lineageTag: a6c632c1-5079-5d7c-8867-6d84c7642324
		sourceColumn: event_count
		formatString: #,0
		summarizeBy: none

	column serious_count
		dataType: int64
		lineageTag: 25538a39-caed-51a9-a960-9a449d5ef91b
		sourceColumn: serious_count
		formatString: #,0
		summarizeBy: none

	column unnotified_serious_count
		dataType: int64
		lineageTag: 8f4825ca-1610-5d33-bda7-90dd646566dd
		sourceColumn: unnotified_serious_count
		formatString: #,0
		summarizeBy: none

	partition ae_by_cohort = m
		mode: import
		source =
				let
				    Source = Csv.Document(Binary.FromText("Y29ob3J0LGV2ZW50X2NvdW50LHNlcmlvdXNfY291bnQsdW5ub3RpZmllZF9zZXJpb3VzX2NvdW50CmJyZWFzdCwxNCwyLDAKbmVydmUsMjAsMiwwCndvdW5kLDE4LDEsMAo=", BinaryEncoding.Base64), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"cohort", type text}, {"event_count", Int64.Type}, {"serious_count", Int64.Type}, {"unnotified_serious_count", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
