table challenge_queries_by_rule
	lineageTag: d7dbf38d-bb56-517e-920f-e3382cde6366

	column rule_id
		dataType: text
		lineageTag: 65455ea5-ed9f-521f-baa6-a200f75994dd
		sourceColumn: rule_id

	column query_count
		dataType: int64
		lineageTag: 6758003f-f40d-5df5-8ec9-cbf67585eafb
		sourceColumn: query_count
		formatString: #,0
		summarizeBy: none

	partition challenge_queries_by_rule = m
		mode: import
		source =
				let
				    Source = Csv.Document(Binary.FromText("cnVsZV9pZCxxdWVyeV9jb3VudApDSFJPTk9MT0dZLDMKQ09IT1JUX01JU01BVENILDMKRk9MTE9XVVBfRFVFLDE1CkZPTExPV1VQX1NUQVRVUywzCk1PRFVMRV9NSVNTSU5HLDMKU0FFX05PVElGSUNBVElPTiwzCg==", BinaryEncoding.Base64), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"rule_id", type text}, {"query_count", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
